import type { SeedExercise } from './beginner-course';
const units = [
  [
    '01 · Yesterday. Past Simple: правильные глаголы',
    'Past Simple описывает завершённое действие в прошлом. К правильному глаголу добавляем -ed: work → worked; после e — только d; study → studied. После did/did not используем начальную форму.',
    [
      ['Last Monday I ___ (visit) my aunt.', 'visited'],
      ['She ___ (work) yesterday.', 'worked'],
      ['We ___ (study) English last night.', 'studied'],
      ['They ___ (play) tennis on Sunday.', 'played'],
      ['He ___ (live) in London in 2020.', 'lived'],
      ['Did you ___ (watch) the film?', 'watch'],
      ['I did not ___ (visit) the museum.', 'visit'],
      ['We ___ (stop) at the station yesterday.', 'stopped'],
    ],
  ],
  [
    '02 · Last weekend. Неправильные глаголы',
    'Past Simple: go → went; see → saw; buy → bought; eat → ate; take → took; have → had; meet → met; get → got.',
    [
      ['Yesterday we ___ (go) to the park.', 'went'],
      ['I ___ (see) Anna last week.', 'saw'],
      ['She ___ (buy) a ticket yesterday.', 'bought'],
      ['They ___ (eat) dinner at six yesterday.', 'ate'],
      ['He ___ (take) the bus yesterday.', 'took'],
      ['We ___ (have) a good time last night.', 'had'],
      ['I ___ (meet) my friend on Monday.', 'met'],
      ['She ___ (get) home late yesterday.', 'got'],
    ],
  ],
  [
    '03 · What were you doing? Past Continuous',
    'Past Continuous: was/were + глагол-ing. Длительное действие в определённый момент прошлого: I was reading at eight. I/he/she/it — was; you/we/they — were.',
    [
      ['At eight yesterday I ___ reading.', 'was'],
      ['At nine yesterday they ___ sleeping.', 'were'],
      ['She was ___ (cook) when I arrived.', 'cooking'],
      ['We were ___ (wait) at six.', 'waiting'],
      ['He ___ not listening at that moment.', 'was'],
      ['You ___ working when I called.', 'were'],
      ['Was she ___ (study) at seven?', 'studying'],
      ['The children were ___ (play) when it started raining.', 'playing'],
    ],
  ],
  [
    '04 · Our plans. Going to и will',
    'Планы: be going to + начальная форма. Прогноз или решение в момент речи: will + начальная форма. После will форма глагола не меняется.',
    [
      ['We are ___ to travel next month.', 'going'],
      ['She ___ going to study tonight.', 'is'],
      ['I ___ going to visit my sister.', 'am'],
      ['They ___ going to buy a car.', 'are'],
      ['I think it will ___ (rain) tomorrow.', 'rain'],
      ['I will ___ (help) you with that bag.', 'help'],
      ['Are you going to ___ (cook) dinner?', 'cook'],
      ['He will not ___ (be) late.', 'be'],
    ],
  ],
  [
    '05 · Bigger and better. Сравнения',
    'Короткие прилагательные: small → smaller → the smallest; big → bigger. Длинные: more/most expensive. Исключения: good → better → best; bad → worse → worst. Сравнение двух предметов: than.',
    [
      ['This bag is ___ (small) than that one.', 'smaller'],
      ['My room is ___ (big) than yours.', 'bigger'],
      ['This train is faster ___ the bus.', 'than'],
      ['This is the ___ (cheap) ticket in the shop.', 'cheapest'],
      ['This hotel is ___ expensive than that one.', 'more'],
      ['This is the ___ expensive hotel in town.', 'most'],
      ['Today the weather is ___ (good) than yesterday.', 'better'],
      ['That was the ___ (bad) day of my holiday.', 'worst'],
    ],
  ],
  [
    '06 · At the market. Количество',
    'Many — с исчисляемыми во множественном числе; much — с неисчисляемыми. Some обычно в утверждениях; any в отрицаниях и нейтральных вопросах. A few — несколько; a little — немного.',
    [
      ['How ___ apples do you need?', 'many'],
      ['How ___ water do you drink?', 'much'],
      ['There are ___ oranges. Выберите some или any.', 'some'],
      ['There is not ___ milk. Выберите some или any.', 'any'],
      ['Do you have ___ questions? Выберите some или any.', 'any'],
      ['We have a ___ eggs. Выберите few или little.', 'few'],
      ['There is a ___ sugar. Выберите few или little.', 'little'],
      ['How ___ people are coming? Выберите much или many.', 'many'],
    ],
  ],
  [
    '07 · Advice and rules. Модальные глаголы',
    'Should — совет; must — обязанность; must not — запрет; do not have to — отсутствие необходимости. После should/must/can ставим начальную форму без to.',
    [
      ['You ___ see a dentist. Совет: используйте should.', 'should'],
      ['You must ___ (wear) a seat belt.', 'wear'],
      ['You must ___ smoke here. Здесь курить запрещено.', 'not'],
      ['You do not ___ to pay. Вход бесплатный.', 'have'],
      ['She ___ to wear a uniform at work. Форма have.', 'has'],
      ['He should ___ (rest) today.', 'rest'],
      ['Can you ___ (help) me?', 'help'],
      ['We should not ___ (be) late.', 'be'],
    ],
  ],
  [
    '08 · Have you ever…? Present Perfect',
    'Present Perfect: have/has + третья форма. I/you/we/they — have; he/she/it — has. ever — когда-либо; never — никогда; yet в вопросах/отрицаниях. go → gone; see → seen; finish → finished.',
    [
      ['I ___ finished my homework.', 'have'],
      ['She ___ visited Paris twice.', 'has'],
      ['Have you ever ___ (see) snow?', 'seen'],
      ['He has ___ (go) home.', 'gone'],
      ['We have ___ (finish) the project.', 'finished'],
      ['They have not arrived ___. Выберите yet или ever.', 'yet'],
      ['Have you ___ tried sushi? Выберите ever или yet.', 'ever'],
      ['I have ___ been to Rome. Никогда: одно слово.', 'never'],
    ],
  ],
  [
    '09 · Since and for. Опыт и время',
    'Since — начальная точка времени; for — длительность. Present Perfect связывает прошлое с настоящим. При указанном завершённом времени yesterday/last year используем Past Simple.',
    [
      ['I have lived here ___ 2020.', 'since'],
      ['She has worked here ___ three years.', 'for'],
      ['We have been friends ___ childhood.', 'since'],
      ['They have waited ___ two hours.', 'for'],
      ['I ___ (visit) Paris last year.', 'visited'],
      ['She has ___ (buy) a new phone.', 'bought'],
      ['We ___ (meet) yesterday.', 'met'],
      ['He has studied English ___ September.', 'since'],
    ],
  ],
  [
    '10 · Around town. Путешествия и направления',
    'Turn left/right — поверните налево/направо; go straight — идите прямо; opposite — напротив; next to — рядом с; platform — платформа; return ticket — билет туда и обратно; reservation — бронирование.',
    [
      ['Turn ___. — Поверните налево.', 'left'],
      ['Turn ___. — Поверните направо.', 'right'],
      ['Go ___ ahead. — Идите прямо.', 'straight'],
      ['The bank is ___ the school. — Банк напротив школы.', 'opposite'],
      ['The cafe is next ___ the station.', 'to'],
      ['Which ___ does the train leave from? — С какой платформы?', 'platform'],
      ['A ___ ticket, please. — Билет туда и обратно.', 'return'],
      ['I have a ___. — У меня есть бронирование.', 'reservation'],
    ],
  ],
  [
    '11 · If it rains. Условия и связки',
    'First Conditional: if + Present Simple, will + начальная форма. Because — потому что; so — поэтому; although — хотя. После when о будущем обычно Present Simple.',
    [
      ['If it ___ (rain), we will stay home.', 'rains'],
      ['If I have time, I ___ call you.', 'will'],
      ['If she ___ (study), she will pass.', 'studies'],
      ['We will ___ (go) out if it is sunny.', 'go'],
      ['I stayed home ___ I was ill. Причина.', 'because'],
      ['I was tired, ___ I went to bed. Следствие.', 'so'],
      ['___ it was cold, we went for a walk. Хотя.', 'although'],
      ['I will call you when I ___ (arrive).', 'arrive'],
    ],
  ],
  [
    '12 · Tell your story. Повторение A2',
    'Повторение: формы прошедшего времени, планы, сравнения, советы и опыт. Читайте контекст и время действия. Введите только пропущенное слово.',
    [
      ['Yesterday I ___ (go) to a new restaurant.', 'went'],
      ['While we were ___ (eat), Anna called.', 'eating'],
      ['Next week we are ___ to visit her.', 'going'],
      ['Her town is ___ (small) than ours.', 'smaller'],
      ['I have ___ (be) there twice.', 'been'],
      ['We have known her ___ five years.', 'for'],
      ['You should ___ (take) an umbrella.', 'take'],
      ['If it rains, we ___ stay inside.', 'will'],
    ],
  ],
] as const;
export const elementaryCourse = {
  title: 'English A2 · Everyday English',
  level: 'A2',
  lessons: units.map(([title, rule, tasks]) => ({
    title,
    exercises: tasks.map(([prompt, answer]): SeedExercise => ({
      type: 'fill_gap',
      question:
        rule +
        '\n\n' +
        prompt +
        '\n\nВведите только пропущенное слово строчными буквами, без точки.',
      options: {},
      correct_answer: answer,
    })),
  })),
};
