/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/chats/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Chats */
    get: operations['get_chats_chats__get'];
    put?: never;
    /** Create Chat */
    post: operations['create_chat_chats__post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/chats/{chat_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Chat */
    get: operations['get_chat_chats__chat_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/chats/{chat_id}/members': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Members */
    get: operations['get_members_chats__chat_id__members_get'];
    put?: never;
    /** Add Member */
    post: operations['add_member_chats__chat_id__members_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/chats/{chat_id}/members/{user_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Remove Member */
    delete: operations['remove_member_chats__chat_id__members__user_id__delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/chats/{chat_id}/messages': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Messages */
    get: operations['get_messages_chats__chat_id__messages_get'];
    put?: never;
    /** Create Message */
    post: operations['create_message_chats__chat_id__messages_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/chats/{chat_id}/messages/{message_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Message */
    get: operations['get_message_chats__chat_id__messages__message_id__get'];
    put?: never;
    post?: never;
    /** Delete Message */
    delete: operations['delete_message_chats__chat_id__messages__message_id__delete'];
    options?: never;
    head?: never;
    /** Update Message */
    patch: operations['update_message_chats__chat_id__messages__message_id__patch'];
    trace?: never;
  };
  '/chats/{chat_id}/messages/{message_id}/read': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Mark Message As Read */
    patch: operations['mark_message_as_read_chats__chat_id__messages__message_id__read_patch'];
    trace?: never;
  };
  '/chats/{chat_id}/messages/{message_id}/reactions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Reactions */
    get: operations['get_reactions_chats__chat_id__messages__message_id__reactions_get'];
    put?: never;
    /** Add Reaction */
    post: operations['add_reaction_chats__chat_id__messages__message_id__reactions_post'];
    /** Remove Reaction */
    delete: operations['remove_reaction_chats__chat_id__messages__message_id__reactions_delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/register': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Register */
    post: operations['register_auth_register_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Login */
    post: operations['login_auth_login_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Logout */
    post: operations['logout_auth_logout_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Refresh */
    post: operations['refresh_auth_refresh_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** User Me */
    get: operations['user_me_users_me_get'];
    /** Update Profile */
    put: operations['update_profile_users_me_put'];
    post?: never;
    /** Delete Profile */
    delete: operations['delete_profile_users_me_delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** User List */
    get: operations['user_list_users__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/{user_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** User Detail */
    get: operations['user_detail_users__user_id__get'];
    put?: never;
    post?: never;
    /** Deactivate User */
    delete: operations['deactivate_user_users__user_id__delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/{user_id}/role': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Change Role */
    patch: operations['change_role_users__user_id__role_patch'];
    trace?: never;
  };
  '/users/{user_id}/active': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Set Active */
    patch: operations['set_active_users__user_id__active_patch'];
    trace?: never;
  };
  '/friends/request': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Send Request */
    post: operations['send_request_friends_request_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/friends/request/{request_id}/accept': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Accept Request */
    post: operations['accept_request_friends_request__request_id__accept_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/friends/request/{request_id}/reject': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Reject Request */
    post: operations['reject_request_friends_request__request_id__reject_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/friends/requests': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Requests */
    get: operations['list_requests_friends_requests_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/friends/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Friends List */
    get: operations['friends_list_friends__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/friends/{friend_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Remove Friend */
    delete: operations['remove_friend_friends__friend_id__delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/courses': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Courses */
    get: operations['get_courses_courses_get'];
    put?: never;
    /** Create Course */
    post: operations['create_course_courses_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/courses/{course_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Course */
    get: operations['get_course_courses__course_id__get'];
    /** Update Course */
    put: operations['update_course_courses__course_id__put'];
    post?: never;
    /** Delete Course */
    delete: operations['delete_course_courses__course_id__delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/courses/language/{language_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Courses By Language */
    get: operations['get_courses_by_language_courses_language__language_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/exercises': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Exercises */
    get: operations['get_exercises_exercises_get'];
    put?: never;
    /** Create Exercise */
    post: operations['create_exercise_exercises_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/exercises/lesson/{lesson_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Exercises By Lesson */
    get: operations['get_exercises_by_lesson_exercises_lesson__lesson_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/exercises/{exercise_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Exercise */
    get: operations['get_exercise_exercises__exercise_id__get'];
    /** Update Exercise */
    put: operations['update_exercise_exercises__exercise_id__put'];
    post?: never;
    /** Delete Exercise */
    delete: operations['delete_exercise_exercises__exercise_id__delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/exercises/{exercise_id}/submit': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Submit Exercise */
    post: operations['submit_exercise_exercises__exercise_id__submit_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/lessons': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Lessons */
    get: operations['get_lessons_lessons_get'];
    put?: never;
    /** Create Lesson */
    post: operations['create_lesson_lessons_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/lessons/course/{course_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Lessons By Course */
    get: operations['get_lessons_by_course_lessons_course__course_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/lessons/{lesson_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Lesson */
    get: operations['get_lesson_lessons__lesson_id__get'];
    /** Update Lesson */
    put: operations['update_lesson_lessons__lesson_id__put'];
    post?: never;
    /** Delete Lesson */
    delete: operations['delete_lesson_lessons__lesson_id__delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/languages': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Languages */
    get: operations['get_languages_languages_get'];
    put?: never;
    /** Create Language */
    post: operations['create_language_languages_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/languages/{language_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Language */
    get: operations['get_language_languages__language_id__get'];
    /** Update Language */
    put: operations['update_language_languages__language_id__put'];
    post?: never;
    /** Delete Language */
    delete: operations['delete_language_languages__language_id__delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/gamification/xp/{user_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Xp History */
    get: operations['get_xp_history_gamification_xp__user_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/gamification/streak/{user_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Streak */
    get: operations['get_streak_gamification_streak__user_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/progress': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Progress */
    get: operations['get_progress_progress_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/progress/user/{user_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get User Progress */
    get: operations['get_user_progress_progress_user__user_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/progress/lesson/{lesson_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Lesson Progress */
    get: operations['get_lesson_progress_progress_lesson__lesson_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/progress/{progress_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Progress By Id */
    get: operations['get_progress_by_id_progress__progress_id__get'];
    /** Update Progress */
    put: operations['update_progress_progress__progress_id__put'];
    post?: never;
    /** Delete Progress */
    delete: operations['delete_progress_progress__progress_id__delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/achievements': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Achievements */
    get: operations['get_achievements_achievements_get'];
    put?: never;
    /** Create Achievement */
    post: operations['create_achievement_achievements_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/achievements/user/{user_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get User Achievements */
    get: operations['get_user_achievements_achievements_user__user_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/achievements/{achievement_id}/award/{user_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Award Achievement */
    post: operations['award_achievement_achievements__achievement_id__award__user_id__post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/achievements/{achievement_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Achievement */
    get: operations['get_achievement_achievements__achievement_id__get'];
    /** Update Achievement */
    put: operations['update_achievement_achievements__achievement_id__put'];
    post?: never;
    /** Delete Achievement */
    delete: operations['delete_achievement_achievements__achievement_id__delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/challenges': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Challenges */
    get: operations['get_challenges_challenges_get'];
    put?: never;
    /** Create Challenge */
    post: operations['create_challenge_challenges_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/challenges/today': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Today Challenge */
    get: operations['get_today_challenge_challenges_today_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/challenges/{challenge_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Challenge */
    get: operations['get_challenge_challenges__challenge_id__get'];
    /** Update Challenge */
    put: operations['update_challenge_challenges__challenge_id__put'];
    post?: never;
    /** Delete Challenge */
    delete: operations['delete_challenge_challenges__challenge_id__delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/leaderboard': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Leaderboard */
    get: operations['get_leaderboard_leaderboard_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/leaderboard/{user_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get User Rank */
    get: operations['get_user_rank_leaderboard__user_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/leaderboard/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Refresh Leaderboard */
    post: operations['refresh_leaderboard_leaderboard_refresh_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/notifications': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Notifications */
    get: operations['get_notifications_notifications_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/notifications/read-all': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Mark All Read */
    patch: operations['mark_all_read_notifications_read_all_patch'];
    trace?: never;
  };
  '/notifications/{notification_id}/read': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Mark Notification Read */
    patch: operations['mark_notification_read_notifications__notification_id__read_patch'];
    trace?: never;
  };
  '/notifications/{notification_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete Notification */
    delete: operations['delete_notification_notifications__notification_id__delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations['health_health_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AchievementCreate */
    AchievementCreate: {
      /** Title */
      title: string;
      /** Description */
      description: string;
      /**
       * Xp Reward
       * @default 0
       */
      xp_reward: number;
      /** Conditions */
      conditions?: {
        [key: string]: unknown;
      } | null;
    };
    /** AchievementResponse */
    AchievementResponse: {
      /** Id */
      id: number;
      /** Title */
      title: string;
      /** Description */
      description: string;
      /** Xp Reward */
      xp_reward: number;
      /** Conditions */
      conditions?: {
        [key: string]: unknown;
      } | null;
    };
    /** AchievementUpdate */
    AchievementUpdate: {
      /** Title */
      title?: string | null;
      /** Description */
      description?: string | null;
      /** Xp Reward */
      xp_reward?: number | null;
      /** Conditions */
      conditions?: {
        [key: string]: unknown;
      } | null;
    };
    /** ActiveUpdateSchema */
    ActiveUpdateSchema: {
      /** Is Active */
      is_active: boolean;
    };
    /** ChallengeCreate */
    ChallengeCreate: {
      /** Title */
      title: string;
      /** Description */
      description: string;
      /**
       * Xp Reward
       * @default 0
       */
      xp_reward: number;
      /**
       * Challenge Date
       * Format: date
       */
      challenge_date: string;
    };
    /** ChallengeResponse */
    ChallengeResponse: {
      /** Id */
      id: number;
      /** Title */
      title: string;
      /** Description */
      description: string;
      /** Xp Reward */
      xp_reward: number;
      /**
       * Challenge Date
       * Format: date
       */
      challenge_date: string;
    };
    /** ChallengeUpdate */
    ChallengeUpdate: {
      /** Title */
      title?: string | null;
      /** Description */
      description?: string | null;
      /** Xp Reward */
      xp_reward?: number | null;
      /** Challenge Date */
      challenge_date?: string | null;
    };
    /** ChatCreate */
    ChatCreate: {
      type: components['schemas']['ChatType'];
      /** Language Id */
      language_id?: number | null;
    };
    /** ChatMemberCreate */
    ChatMemberCreate: {
      /**
       * User Id
       * Format: uuid
       */
      user_id: string;
    };
    /** ChatMemberResponse */
    ChatMemberResponse: {
      /**
       * Chat Id
       * Format: uuid
       */
      chat_id: string;
      /**
       * User Id
       * Format: uuid
       */
      user_id: string;
      /**
       * Joined At
       * Format: date-time
       */
      joined_at: string;
    };
    /** ChatResponse */
    ChatResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      type: components['schemas']['ChatType'];
      /** Language Id */
      language_id: number | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /**
     * ChatType
     * @enum {string}
     */
    ChatType: 'private' | 'group';
    /** CourseCreate */
    CourseCreate: {
      /** Language Id */
      language_id: number;
      /** Title */
      title: string;
      /** Description */
      description: string;
      level: components['schemas']['LevelChoices'];
      /** Order */
      order: number;
    };
    /** CourseResponse */
    CourseResponse: {
      /** Id */
      id: number;
      /** Language Id */
      language_id: number;
      /** Title */
      title: string;
      /** Description */
      description: string;
      level: components['schemas']['LevelChoices'];
      /** Order */
      order: number;
    };
    /** CourseUpdate */
    CourseUpdate: {
      /** Language Id */
      language_id?: number | null;
      /** Title */
      title?: string | null;
      /** Description */
      description?: string | null;
      level?: components['schemas']['LevelChoices'] | null;
      /** Order */
      order?: number | null;
    };
    /** ExerciseCreate */
    ExerciseCreate: {
      /** Lesson Id */
      lesson_id: number;
      type: components['schemas']['ExerciseType'];
      /** Question */
      question: string;
      /** Options */
      options: {
        [key: string]: unknown;
      };
      /** Correct Answer */
      correct_answer: unknown;
    };
    /** ExerciseResponse */
    ExerciseResponse: {
      /** Id */
      id: number;
      /** Lesson Id */
      lesson_id: number;
      type: components['schemas']['ExerciseType'];
      /** Question */
      question: string;
      /** Options */
      options: {
        [key: string]: unknown;
      };
    };
    /** ExerciseResult */
    ExerciseResult: {
      /** Correct */
      correct: boolean;
      /** Score */
      score: number;
    };
    /** ExerciseSubmit */
    ExerciseSubmit: {
      /** Answer */
      answer: unknown;
    };
    /**
     * ExerciseType
     * @enum {string}
     */
    ExerciseType: 'choice' | 'translate' | 'fill_gap' | 'match';
    /** ExerciseUpdate */
    ExerciseUpdate: {
      /** Lesson Id */
      lesson_id?: number | null;
      type?: components['schemas']['ExerciseType'] | null;
      /** Question */
      question?: string | null;
      /** Options */
      options?: {
        [key: string]: unknown;
      } | null;
      /** Correct Answer */
      correct_answer?: unknown | null;
    };
    /** FriendRequestCreate */
    FriendRequestCreate: {
      /**
       * Receiver Id
       * Format: uuid
       */
      receiver_id: string;
    };
    /** FriendRequestResponse */
    FriendRequestResponse: {
      /** Id */
      id: number;
      /**
       * Sender Id
       * Format: uuid
       */
      sender_id: string;
      /**
       * Receiver Id
       * Format: uuid
       */
      receiver_id: string;
      /** Status */
      status: string;
    };
    /** FriendResponse */
    FriendResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Username */
      username: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /** LanguageCreate */
    LanguageCreate: {
      /** Code */
      code: string;
      /** Name */
      name: string;
      /**
       * Is Active
       * @default false
       */
      is_active: boolean;
    };
    /** LanguageResponse */
    LanguageResponse: {
      /** Id */
      id: number;
      /** Code */
      code: string;
      /** Name */
      name: string;
      /** Is Active */
      is_active: boolean;
    };
    /** LanguageUpdate */
    LanguageUpdate: {
      /** Code */
      code?: string | null;
      /** Name */
      name?: string | null;
      /** Is Active */
      is_active?: boolean | null;
    };
    /** LeaderboardResponse */
    LeaderboardResponse: {
      /**
       * User Id
       * Format: uuid
       */
      user_id: string;
      /** Xp */
      xp: number;
      /** Rank */
      rank: number;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** LessonCreate */
    LessonCreate: {
      /** Course Id */
      course_id: number;
      /** Title */
      title: string;
      /** Order */
      order: number;
      /**
       * Is Locked
       * @default false
       */
      is_locked: boolean;
    };
    /** LessonResponse */
    LessonResponse: {
      /** Id */
      id: number;
      /** Course Id */
      course_id: number;
      /** Title */
      title: string;
      /** Order */
      order: number;
      /** Is Locked */
      is_locked: boolean;
    };
    /** LessonUpdate */
    LessonUpdate: {
      /** Course Id */
      course_id?: number | null;
      /** Title */
      title?: string | null;
      /** Order */
      order?: number | null;
      /** Is Locked */
      is_locked?: boolean | null;
    };
    /**
     * LevelChoices
     * @enum {string}
     */
    LevelChoices: 'A1' | 'A2' | 'B1' | 'B2' | 'C1' | 'C2';
    /** LoginSchema */
    LoginSchema: {
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Password */
      password: string;
    };
    /** MessageCreate */
    MessageCreate: {
      /** Content */
      content: string;
    };
    /** MessageResponse */
    MessageResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Chat Id
       * Format: uuid
       */
      chat_id: string;
      /**
       * Sender Id
       * Format: uuid
       */
      sender_id: string;
      /** Content */
      content: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Is Read */
      is_read: boolean;
    };
    /** MessageUpdate */
    MessageUpdate: {
      /** Content */
      content: string;
    };
    /** NotificationResponse */
    NotificationResponse: {
      /** Id */
      id: number;
      /**
       * User Id
       * Format: uuid
       */
      user_id: string;
      type: components['schemas']['NotificationType'];
      /** Title */
      title: string;
      /** Message */
      message: string;
      /** Is Read */
      is_read: boolean;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /**
     * NotificationType
     * @enum {string}
     */
    NotificationType: 'friend_request' | 'achievement' | 'message' | 'system';
    /** ProgressResponse */
    ProgressResponse: {
      /** Id */
      id: number;
      /**
       * User Id
       * Format: uuid
       */
      user_id: string;
      /** Lesson Id */
      lesson_id: number;
      /** Completed */
      completed: boolean;
      /** Score */
      score: number;
      /** Completed At */
      completed_at?: string | null;
    };
    /** ProgressUpdate */
    ProgressUpdate: {
      /** Completed */
      completed?: boolean | null;
      /** Score */
      score?: number | null;
    };
    /** ReactionCreate */
    ReactionCreate: {
      /** Reaction */
      reaction: string;
    };
    /** ReactionResponse */
    ReactionResponse: {
      /** Id */
      id: number;
      /**
       * Message Id
       * Format: uuid
       */
      message_id: string;
      /**
       * User Id
       * Format: uuid
       */
      user_id: string;
      /** Reaction */
      reaction: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** RefreshSchema */
    RefreshSchema: {
      /** Refresh Token */
      refresh_token: string;
    };
    /** RegisterSchema */
    RegisterSchema: {
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Username */
      username: string;
      /** Password */
      password: string;
    };
    /** RoleUpdateSchema */
    RoleUpdateSchema: {
      role: components['schemas']['UserRole'];
    };
    /** StreakResponse */
    StreakResponse: {
      /** Id */
      id: number;
      /**
       * User Id
       * Format: uuid
       */
      user_id: string;
      /** Current Streak */
      current_streak: number;
      /** Last Activity */
      last_activity?: string | null;
    };
    /** TokenSchema */
    TokenSchema: {
      /** Access Token */
      access_token: string;
      /** Refresh Token */
      refresh_token: string;
      /**
       * Token Type
       * @default bearer
       */
      token_type: string;
    };
    /** UserAchievementResponse */
    UserAchievementResponse: {
      /** Id */
      id: number;
      /**
       * User Id
       * Format: uuid
       */
      user_id: string;
      /** Achievement Id */
      achievement_id: number;
      /**
       * Earned At
       * Format: date-time
       */
      earned_at: string;
    };
    /** UserLeaderboardResponse */
    UserLeaderboardResponse: {
      /**
       * User Id
       * Format: uuid
       */
      user_id: string;
      /** Xp */
      xp: number;
      /** Rank */
      rank?: number | null;
    };
    /** UserResponseSchema */
    UserResponseSchema: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Username */
      username: string;
      role: components['schemas']['UserRole'];
      /** Is Active */
      is_active: boolean;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /**
     * UserRole
     * @enum {string}
     */
    UserRole: 'user' | 'admin';
    /** UserUpdateSchema */
    UserUpdateSchema: {
      /** Username */
      username?: string | null;
      /** Email */
      email?: string | null;
      /** Password */
      password?: string | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
    /** XPHistoryResponse */
    XPHistoryResponse: {
      /** Id */
      id: number;
      /**
       * User Id
       * Format: uuid
       */
      user_id: string;
      /** Xp */
      xp: number;
      /** Reason */
      reason: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  get_chats_chats__get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ChatResponse'][];
        };
      };
    };
  };
  create_chat_chats__post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ChatCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ChatResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_chat_chats__chat_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        chat_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ChatResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_members_chats__chat_id__members_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        chat_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ChatMemberResponse'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  add_member_chats__chat_id__members_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        chat_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ChatMemberCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ChatMemberResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  remove_member_chats__chat_id__members__user_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        chat_id: string;
        user_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_messages_chats__chat_id__messages_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        chat_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MessageResponse'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_message_chats__chat_id__messages_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        chat_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['MessageCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MessageResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_message_chats__chat_id__messages__message_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        chat_id: string;
        message_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MessageResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_message_chats__chat_id__messages__message_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        chat_id: string;
        message_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_message_chats__chat_id__messages__message_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        chat_id: string;
        message_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['MessageUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MessageResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  mark_message_as_read_chats__chat_id__messages__message_id__read_patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        chat_id: string;
        message_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MessageResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_reactions_chats__chat_id__messages__message_id__reactions_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        chat_id: string;
        message_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ReactionResponse'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  add_reaction_chats__chat_id__messages__message_id__reactions_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        chat_id: string;
        message_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ReactionCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ReactionResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  remove_reaction_chats__chat_id__messages__message_id__reactions_delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        chat_id: string;
        message_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ReactionCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  register_auth_register_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RegisterSchema'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserResponseSchema'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  login_auth_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginSchema'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TokenSchema'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  logout_auth_logout_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RefreshSchema'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  refresh_auth_refresh_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RefreshSchema'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  user_me_users_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserResponseSchema'];
        };
      };
    };
  };
  update_profile_users_me_put: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UserUpdateSchema'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserResponseSchema'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_profile_users_me_delete: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  user_list_users__get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserResponseSchema'][];
        };
      };
    };
  };
  user_detail_users__user_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserResponseSchema'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  deactivate_user_users__user_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  change_role_users__user_id__role_patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RoleUpdateSchema'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserResponseSchema'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  set_active_users__user_id__active_patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ActiveUpdateSchema'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserResponseSchema'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  send_request_friends_request_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['FriendRequestCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FriendRequestResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  accept_request_friends_request__request_id__accept_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        request_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FriendRequestResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  reject_request_friends_request__request_id__reject_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        request_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FriendRequestResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_requests_friends_requests_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FriendRequestResponse'][];
        };
      };
    };
  };
  friends_list_friends__get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FriendResponse'][];
        };
      };
    };
  };
  remove_friend_friends__friend_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        friend_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_courses_courses_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CourseResponse'][];
        };
      };
    };
  };
  create_course_courses_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CourseCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CourseResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_course_courses__course_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        course_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CourseResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_course_courses__course_id__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        course_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CourseUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CourseResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_course_courses__course_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        course_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_courses_by_language_courses_language__language_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        language_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CourseResponse'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_exercises_exercises_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ExerciseResponse'][];
        };
      };
    };
  };
  create_exercise_exercises_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ExerciseCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ExerciseResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_exercises_by_lesson_exercises_lesson__lesson_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        lesson_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ExerciseResponse'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_exercise_exercises__exercise_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        exercise_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ExerciseResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_exercise_exercises__exercise_id__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        exercise_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ExerciseUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ExerciseResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_exercise_exercises__exercise_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        exercise_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  submit_exercise_exercises__exercise_id__submit_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        exercise_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ExerciseSubmit'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ExerciseResult'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_lessons_lessons_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LessonResponse'][];
        };
      };
    };
  };
  create_lesson_lessons_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LessonCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LessonResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_lessons_by_course_lessons_course__course_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        course_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LessonResponse'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_lesson_lessons__lesson_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        lesson_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LessonResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_lesson_lessons__lesson_id__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        lesson_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LessonUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LessonResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_lesson_lessons__lesson_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        lesson_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_languages_languages_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LanguageResponse'][];
        };
      };
    };
  };
  create_language_languages_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LanguageCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LanguageResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_language_languages__language_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        language_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LanguageResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_language_languages__language_id__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        language_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LanguageUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LanguageResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_language_languages__language_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        language_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_xp_history_gamification_xp__user_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['XPHistoryResponse'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_streak_gamification_streak__user_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['StreakResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_progress_progress_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProgressResponse'][];
        };
      };
    };
  };
  get_user_progress_progress_user__user_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProgressResponse'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_lesson_progress_progress_lesson__lesson_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        lesson_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProgressResponse'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_progress_by_id_progress__progress_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        progress_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProgressResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_progress_progress__progress_id__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        progress_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ProgressUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProgressResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_progress_progress__progress_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        progress_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_achievements_achievements_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AchievementResponse'][];
        };
      };
    };
  };
  create_achievement_achievements_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AchievementCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AchievementResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_user_achievements_achievements_user__user_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserAchievementResponse'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  award_achievement_achievements__achievement_id__award__user_id__post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        achievement_id: number;
        user_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserAchievementResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_achievement_achievements__achievement_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        achievement_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AchievementResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_achievement_achievements__achievement_id__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        achievement_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AchievementUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AchievementResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_achievement_achievements__achievement_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        achievement_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_challenges_challenges_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ChallengeResponse'][];
        };
      };
    };
  };
  create_challenge_challenges_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ChallengeCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ChallengeResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_today_challenge_challenges_today_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ChallengeResponse'];
        };
      };
    };
  };
  get_challenge_challenges__challenge_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        challenge_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ChallengeResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_challenge_challenges__challenge_id__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        challenge_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ChallengeUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ChallengeResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_challenge_challenges__challenge_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        challenge_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_leaderboard_leaderboard_get: {
    parameters: {
      query?: {
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LeaderboardResponse'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_user_rank_leaderboard__user_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserLeaderboardResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  refresh_leaderboard_leaderboard_refresh_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  get_notifications_notifications_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['NotificationResponse'][];
        };
      };
    };
  };
  mark_all_read_notifications_read_all_patch: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  mark_notification_read_notifications__notification_id__read_patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        notification_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['NotificationResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_notification_notifications__notification_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        notification_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  health_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
}
